[{"directory":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103","file":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103\\lib\\system_stm32f10x.c","command":"\"C:\\Users\\lisha\\.eide\\tools\\gcc_arm\\bin\\arm-none-eabi-gcc.exe\"
-c -xc -mthumb -std=c11 -I.eide/deps -Ilib/cmsis -Ilib -Irts_os 
-Isrc -DSTM32F10X_MD -D__CHECK_DEVICE_DEFINES -D__CM3_REV
-mcpu=cortex-m3 -O2 -Wall -g -ffunction-sections -fdata-sections
--specs=nosys.specs --specs=nano.specs 
-o ./build/Debug/lib/system_stm32f10x.o 
-MMD ./lib/system_stm32f10x.c"},

{"directory":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103",
"file":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103\\rts_os\\rts_core.c",
"command":"\"C:\\Users\\lisha\\.eide\\tools\\gcc_arm\\bin\\arm-none-eabi-gcc.exe\"
-c -xc -mthumb -std=c11 -I.eide/deps -Ilib/cmsis -Ilib -Irts_os
-Isrc -DSTM32F10X_MD -D__CHECK_DEVICE_DEFINES -D__CM3_REV -mcpu=cortex-m3 
-O2 -Wall -g -ffunction-sections -fdata-sections --specs=nosys.specs 
--specs=nano.specs -o ./build/Debug/rts_os/rts_core.o 
-MMD ./rts_os/rts_core.c"},{"directory":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103",
"file":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103\\rts_os\\rts_heap1.c",
"command":"\"C:\\Users\\lisha\\.eide\\tools\\gcc_arm\\bin\\arm-none-eabi-gcc.exe\" 
-c -xc -mthumb -std=c11 -I.eide/deps -Ilib/cmsis -Ilib -Irts_os -Isrc 
-DSTM32F10X_MD -D__CHECK_DEVICE_DEFINES -D__CM3_REV -mcpu=cortex-m3 -O2 -Wall 
-g -ffunction-sections -fdata-sections --specs=nosys.specs --specs=nano.specs -o 
./build/Debug/rts_os/rts_heap1.o -MMD ./rts_os/rts_heap1.c"},

{"directory":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103",
"file":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103\\rts_os\\rts_os.c",
"command":"\"C:\\Users\\lisha\\.eide\\tools\\gcc_arm\\bin\\arm-none-eabi-gcc.exe\" 
-c -xc -mthumb -std=c11 -I.eide/deps -Ilib/cmsis -Ilib -Irts_os -Isrc -DSTM32F10X_MD 
-D__CHECK_DEVICE_DEFINES -D__CM3_REV -mcpu=cortex-m3 -O2 -Wall -g -ffunction-sections 
-fdata-sections --specs=nosys.specs --specs=nano.specs 
-o ./build/Debug/rts_os/rts_os.o -MMD ./rts_os/rts_os.c"},

{"directory":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103",
"file":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103\\rts_os\\rts_port.c",
"command":"\"C:\\Users\\lisha\\.eide\\tools\\gcc_arm\\bin\\arm-none-eabi-gcc.exe\" 
-c -xc -mthumb -std=c11 -I.eide/deps -Ilib/cmsis -Ilib -Irts_os -Isrc -DSTM32F10X_MD 
-D__CHECK_DEVICE_DEFINES -D__CM3_REV -mcpu=cortex-m3 -O2 -Wall 
-g -ffunction-sections -fdata-sections --specs=nosys.specs --specs=nano.specs 
-o ./build/Debug/rts_os/rts_port.o -MMD ./rts_os/rts_port.c"},

{"directory":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103",
"file":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103\\rts_os\\rts_port_asm.S",
"command":"\"C:\\Users\\lisha\\.eide\\tools\\gcc_arm\\bin\\arm-none-eabi-gcc.exe\" 
-c -x assembler-with-cpp -mthumb -I.eide/deps -Ilib/cmsis -Ilib -Irts_os -Isrc 
-mcpu=cortex-m3 -g -ffunction-sections -fdata-sections --specs=nosys.specs 
--specs=nano.specs -o ./build/Debug/rts_os/rts_port_asm.o -MMD ./rts_os/rts_port_asm.S"},

{"directory":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103",
"file":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103\\rts_os\\rts_semaphore.c",
"command":"\"C:\\Users\\lisha\\.eide\\tools\\gcc_arm\\bin\\arm-none-eabi-gcc.exe\" 
-c -xc -mthumb -std=c11 -I.eide/deps -Ilib/cmsis -Ilib -Irts_os -Isrc -DSTM32F10X_MD 
-D__CHECK_DEVICE_DEFINES -D__CM3_REV -mcpu=cortex-m3 -O2 -Wall -g -ffunction-sections -fdata-sections 
--specs=nosys.specs --specs=nano.specs -o ./build/Debug/rts_os/rts_semaphore.o 
-MMD ./rts_os/rts_semaphore.c"},

{"directory":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103",
"file":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103\\rts_os\\rts_task.c",
"command":"\"C:\\Users\\lisha\\.eide\\tools\\gcc_arm\\bin\\arm-none-eabi-gcc.exe\" -c -xc 
-mthumb -std=c11 -I.eide/deps -Ilib/cmsis -Ilib -Irts_os -Isrc -DSTM32F10X_MD -D__CHECK_DEVICE_DEFINES 
-D__CM3_REV -mcpu=cortex-m3 -O2 -Wall -g -ffunction-sections -fdata-sections --specs=nosys.specs 
--specs=nano.specs -o ./build/Debug/rts_os/rts_task.o -MMD ./rts_os/rts_task.c"},

{"directory":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103",
"file":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103\\src\\FFT_256.c",
"command":"\"C:\\Users\\lisha\\.eide\\tools\\gcc_arm\\bin\\arm-none-eabi-gcc.exe\" 
-c -xc -mthumb -std=c11 -I.eide/deps -Ilib/cmsis -Ilib -Irts_os -Isrc -DSTM32F10X_MD 
-D__CHECK_DEVICE_DEFINES -D__CM3_REV -mcpu=cortex-m3 -O2 -Wall -g -ffunction-sections 
-fdata-sections --specs=nosys.specs --specs=nano.specs -o ./build/Debug/src/FFT_256.o 
-MMD ./src/FFT_256.c"},

{"directory":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103",
"file":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103\\src\\ILI9341.c",
"command":"\"C:\\Users\\lisha\\.eide\\tools\\gcc_arm\\bin\\arm-none-eabi-gcc.exe\" -c 
-xc -mthumb -std=c11 -I.eide/deps -Ilib/cmsis -Ilib -Irts_os -Isrc -DSTM32F10X_MD 
-D__CHECK_DEVICE_DEFINES -D__CM3_REV -mcpu=cortex-m3 -O2 -Wall -g -ffunction-sections 
-fdata-sections --specs=nosys.specs --specs=nano.specs -o ./build/Debug/src/ILI9341.o 
-MMD ./src/ILI9341.c"},

{"directory":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103",
"file":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103\\src\\LcdGUI.c",
"command":"\"C:\\Users\\lisha\\.eide\\tools\\gcc_arm\\bin\\arm-none-eabi-gcc.exe\" 
-c -xc -mthumb -std=c11 -I.eide/deps -Ilib/cmsis -Ilib -Irts_os -Isrc -DSTM32F10X_MD 
-D__CHECK_DEVICE_DEFINES -D__CM3_REV -mcpu=cortex-m3 -O2 -Wall -g -ffunction-sections 
-fdata-sections --specs=nosys.specs --specs=nano.specs -o ./build/Debug/src/LcdGUI.o 
-MMD ./src/LcdGUI.c"},

{"directory":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103",
"file":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103\\src\\USART.c",
"command":"\"C:\\Users\\lisha\\.eide\\tools\\gcc_arm\\bin\\arm-none-eabi-gcc.exe\" 
-c -xc -mthumb -std=c11 -I.eide/deps -Ilib/cmsis -Ilib -Irts_os -Isrc -DSTM32F10X_MD 
-D__CHECK_DEVICE_DEFINES -D__CM3_REV -mcpu=cortex-m3 -O2 -Wall -g -ffunction-sections 
-fdata-sections --specs=nosys.specs --specs=nano.specs -o ./build/Debug/src/USART.o -MMD 
./src/USART.c"},

{"directory":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103",
"file":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103\\src\\main.c",
"command":"\"C:\\Users\\lisha\\.eide\\tools\\gcc_arm\\bin\\arm-none-eabi-gcc.exe\" 
-c -xc -mthumb -std=c11 -I.eide/deps -Ilib/cmsis -Ilib -Irts_os -Isrc -DSTM32F10X_MD 
-D__CHECK_DEVICE_DEFINES -D__CM3_REV -mcpu=cortex-m3 -O2 -Wall -g -ffunction-sections 
-fdata-sections --specs=nosys.specs --specs=nano.specs -o ./build/Debug/src/main.o -MMD 
./src/main.c"},

{"directory":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103",
"file":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103\\src\\startup_stm32f10x_md.s",
"command":"\"C:\\Users\\lisha\\.eide\\tools\\gcc_arm\\bin\\arm-none-eabi-gcc.exe\" -c 
-x assembler-with-cpp -mthumb -I.eide/deps -Ilib/cmsis -Ilib -Irts_os -Isrc -mcpu=cortex-m3 
-g -ffunction-sections -fdata-sections --specs=nosys.specs --specs=nano.specs 
-o ./build/Debug/src/startup_stm32f10x_md.o -MMD ./src/startup_stm32f10x_md.s"},

{"directory":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103",
"file":"c:\\Users\\lisha\\Desktop\\RT_Plain\\RT_PlainOS-STM32F103\\src\\stm32f10x_it.c",
"command":"\"C:\\Users\\lisha\\.eide\\tools\\gcc_arm\\bin\\arm-none-eabi-gcc.exe\" -c -xc 
-mthumb -std=c11 -I.eide/deps -Ilib/cmsis -Ilib -Irts_os -Isrc -DSTM32F10X_MD -D__CHECK_DEVICE_DEFINES 
-D__CM3_REV -mcpu=cortex-m3 -O2 -Wall -g -ffunction-sections -fdata-sections --specs=nosys.specs 
--specs=nano.specs -o ./build/Debug/src/stm32f10x_it.o -MMD ./src/stm32f10x_it.c"}]




ARCH  := arm
CHIP  := stm32f103c8t6
CSRCS :=
TOPDIR := .

-include arch/$(ARCH)/$(CHIP)/*.mk
-include core/core.mk

LD_SCRIPT := $(TOPDIR)/$(ARCH)/$(CHIP)/$(CHIP).ld


CSRC_OBJS := $(addprefix out/,$(CSRCS))

all:
	@echo $(SRC_FOLDER)
	@echo $(CSRC_OBJS)
	@echo $(LD_SCRIPT)