#ifndef __PLAINOS_CONFIG_H__
#define __PLAINOS_CONFIG_H__

#define CONFIG_PL_ASSERT
#define CONFIG_PL_OS_CHAR_LOGO
#define CONFIG_PL_CHECK_STACK_OVERFLOW
#define CONFIG_PL_CHECK_STACK_OVERFLOW_MAGIC ((uintptr_t)(0xabadc0de))
#define CONFIG_PL_SHELL_SUPPORT
#define CONFIG_PL_SHELL_PREFIX_NAME "plsh"
#define CONFIG_PL_SHELL_CMD_BUFF_MAX (128)
#define CONFIG_PL_SHELL_CMD_ARGC_MAX (20)
#define CONFIG_PL_SHELL_CMD_EXEC_TASK_PRIORITY (90)
#define CONFIG_PL_SHELL_CMD_EXEC_TASK_STACK_SIZE (1024)
#define CONFIG_PL_SYSTICK_TIME_SLICE_US (15)
#define CONFIG_PL_DEFAULT_MEMPOOL_SIZE (14*1024)
#define CONFIG_PL_DEFAULT_MEMPOOL_GRAIN_ORDER (5)
#define CONFIG_PL_MAX_TASKS_NUM (900u)
#define CONFIG_PL_SYS_RSVD_HIGHEST_PRIOTITY (2u)
#define CONFIG_PL_TASK_PRIORITIES_MAX (99u)
#define CONFIG_PL_INIT_TASK_STACK_SIZE (512)
#define CONFIG_PL_IDLE_TASK_STACK_SIZE (512)
#define CONFIG_PL_CPU_RATE_INTERVAL_TICKS (102400)
#define CONFIG_PL_SOFTTIMER_DAEMON_TASK_STACK_SIZE (512)
#define CONFIG_PL_HI_WORKQUEUE_TASK_STACK_SIZE (512)
#define CONFIG_PL_HI_WORKQUEUE_FIFO_CAPACITY (128)
#define CONFIG_PL_LO_WORKQUEUE_TASK_STACK_SIZE (1024)
#define CONFIG_PL_LO_WORKQUEUE_TASK_PRIORITY (CONFIG_PL_TASK_PRIORITIES_MAX)
#define CONFIG_PL_LO_WORKQUEUE_FIFO_CAPACITY (128)

#endif /* __PLAINOS_CONFIG_H__ */
